serenity.project.name=proyecto_v1
serenity.outputDirectory = ./target/serenity
serenity.report.encoding = UTF-8
serenity.issues.tracker = none
serenity.test.root = features
serenity.report.show.step.details = true
